import os

from app.config import (
    IPSEC_CONF_PATH, XL2TPD_CONF_PATH, XL2TPD_PPP_OPTIONS_PATH, NGINX_STREAM_CONF_PATH, DEV_MODE
)
from app.models import Node, Connection


def build_ipsec_conf(nodes: list[Node]) -> str:
    lines = [
        "# --- Auto-generated by the panel - do not edit this file manually ---",
        "config setup",
        "\tuniqueids=no",
        "",
    ]
    for node in nodes:
        lines += [
            f"conn {node.label}",
            "\tauthby=secret",
            "\tkeyexchange=ikev2",
            "\tike=aes256-sha256-modp2048!",
            "\tesp=aes256-sha256!",
            "\ttype=transport",
            "\tleft=%defaultroute",
            "\tleftprotoport=17/1701",
            "\tright=%any",
            f"\trightid=@{node.label}",
            "\trightprotoport=17/%any",
            "\tauto=add",
            "\tforceencaps=yes",
            "",
        ]
    return "\n".join(lines)


def build_xl2tpd_conf(nodes: list[Node]) -> str:
    """
    Note: the L2TP protocol itself runs on one global listener (UDP 1701),
    not a separate block per node. Each node's dedicated IP (tunnel_ip) is
    assigned via the 4th column of chap-secrets (rebuild_secret_files).
    For guaranteed, scalable assignment down the line, the phase-3 report
    suggests migrating to RADIUS - that's out of scope for this MVP.
    """
    ip_pool_note = ", ".join(n.tunnel_ip for n in nodes) if nodes else "no nodes registered yet"
    lines = [
        "; --- Auto-generated by the panel - do not edit this file manually ---",
        f"; Current node tunnel IPs: {ip_pool_note}",
        "[global]",
        "port = 1701",
        "",
        "[lns default]",
        "ip range = 10.10.10.100-10.10.10.200",
        "local ip = 10.10.10.1",
        "require chap = yes",
        "refuse pap = yes",
        "require authentication = yes",
        "name = CentralL2TPServer",
        "ppp debug = no",
        "pppoptfile = /etc/ppp/options.xl2tpd",
        "length bit = yes",
        "",
    ]
    return "\n".join(lines)


def build_ppp_options() -> str:
    lines = [
        "ipcp-accept-local",
        "ipcp-accept-remote",
        "require-chap",
        "refuse-pap",
        "refuse-eap",
        "noccp",
        "auth",
        "crtscts",
        "idle 1800",
        "mtu 1400",
        "mru 1400",
        "nodefaultroute",
        "debug",
        "proxyarp",
        "connect-delay 5000",
    ]
    return "\n".join(lines)


def build_nginx_stream_conf(connections: list[Connection], nodes_by_id: dict) -> str:
    lines = ["# --- Auto-generated by the panel - only connections with L7 proxy enabled ---"]
    for c in connections:
        if not c.enable_l7_proxy or not c.port:
            continue
        target = nodes_by_id.get(c.target_node_id)
        if not target:
            continue
        # Use the target's tunnel_ip as the upstream (not the whole subnet)
        lines.append(f"# Route: {c.label} ({c.mode.value})")
        lines.append("server {")
        lines.append(f"    listen {c.port};")
        if c.mode.value == "one_way":
            src = nodes_by_id.get(c.source_node_id)
            src_ip = src.tunnel_ip if src else "0.0.0.0/0"
            lines.append(f"    allow {src_ip};")
            lines.append("    deny all;")
        lines.append(f"    proxy_pass {target.tunnel_ip}:{c.port};")
        lines.append("}")
        lines.append("")
    return "\n".join(lines)


def _write(path, content: str):
    if DEV_MODE:
        return {"applied": False, "path": str(path), "content": content}
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write(content)
    return {"applied": True, "path": str(path), "content": content}


def rebuild_all_configs(nodes: list[Node], connections: list[Connection]) -> dict:
    nodes_by_id = {n.id: n for n in nodes}
    ipsec_content = build_ipsec_conf(nodes)
    xl2tpd_content = build_xl2tpd_conf(nodes)
    ppp_options_content = build_ppp_options()
    nginx_content = build_nginx_stream_conf(connections, nodes_by_id)

    return {
        "ipsec_conf": _write(IPSEC_CONF_PATH, ipsec_content),
        "xl2tpd_conf": _write(XL2TPD_CONF_PATH, xl2tpd_content),
        "ppp_options": _write(XL2TPD_PPP_OPTIONS_PATH, ppp_options_content),
        "nginx_stream_conf": _write(NGINX_STREAM_CONF_PATH, nginx_content),
    }
