import os
import secrets
import string

from app.config import IPSEC_SECRETS_PATH, CHAP_SECRETS_PATH, SECRETS_DIR, DEV_MODE
from app.crypto_utils import encrypt_str, decrypt_str
from app.models import Node

ALPHABET = string.ascii_letters + string.digits


def generate_secret(length: int = 32) -> str:
    return "".join(secrets.choice(ALPHABET) for _ in range(length))


def issue_node_credentials(node: Node) -> tuple[str, str]:
    """
    Generates a new random PSK and PPP password for a freshly created node
    (or on rotate), sets the encrypted version on the node object itself
    (must be committed by the caller), and returns the plaintext version
    once so the panel can show it to the admin exactly one time.
    """
    psk_plain = generate_secret(32)
    ppp_password_plain = generate_secret(24)

    node.encrypted_psk = encrypt_str(psk_plain)
    node.encrypted_ppp_password = encrypt_str(ppp_password_plain)

    return psk_plain, ppp_password_plain


def _atomic_write(path, content: str, mode: int = 0o600):
    tmp_path = f"{path}.tmp"
    with open(tmp_path, "w") as f:
        f.write(content)
    os.chmod(tmp_path, mode)
    os.replace(tmp_path, path)


def rebuild_secret_files(nodes: list[Node]) -> dict:
    """
    Fully rebuilds ipsec.secrets and chap-secrets from the database. In
    DEV_MODE (no root access to the real system paths), it just returns the
    generated content (dry-run) so it can be reviewed.
    """
    ipsec_lines = ["# --- Auto-generated by the panel - do not edit this file manually ---"]
    chap_lines = ["# --- Auto-generated by the panel - do not edit this file manually ---",
                  "# client\tserver\tsecret\tIP addresses"]

    for node in nodes:
        if not node.encrypted_psk or not node.encrypted_ppp_password:
            continue
        psk = decrypt_str(node.encrypted_psk)
        ppp_password = decrypt_str(node.encrypted_ppp_password)

        # Each node is identified in IPsec by @label (not by public IP, since
        # branch routers may have dynamic IPs - per the phase-3 report's note)
        ipsec_lines.append(f'@{node.label} : PSK "{psk}"')

        # The 4th column specifies that node's dedicated tunnel address
        chap_lines.append(f'{node.label}\t*\t"{ppp_password}"\t{node.tunnel_ip}')

    ipsec_content = "\n".join(ipsec_lines) + "\n"
    chap_content = "\n".join(chap_lines) + "\n"

    if DEV_MODE:
        return {"applied": False, "ipsec_secrets": ipsec_content, "chap_secrets": chap_content}

    os.makedirs(SECRETS_DIR, exist_ok=True)
    _atomic_write(IPSEC_SECRETS_PATH, ipsec_content)
    _atomic_write(CHAP_SECRETS_PATH, chap_content)
    return {"applied": True, "ipsec_secrets": ipsec_content, "chap_secrets": chap_content}
